import type { Metadata } from "next";
import vazirFont from "constants/localFont";
import "styles/globals.css";
import { ReactNode } from "react";
import { QueryProvider } from "providers/query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="fa" className={`${vazirFont.variable} font-sans`}>
      <body className="min-h-full"><QueryProvider>{children}</QueryProvider></body>
    </html>
  );
}
